name: wifi_analyzer
description: a wifi analyzing tool
publish_to: 'none'

version: 1.0.2+2

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  wifi_scan: ^0.4.0+1
  fl_chart: ^0.63.0
  flutter_bloc: ^8.1.3
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
